apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-be
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ecommerce-be
  template:
    metadata:
      labels:
        app: ecommerce-be
    spec:
      containers:
        - name: ecommerce-be-container
          image: xhulioisufi/ecommerce:v1
          ports:
            - containerPort: 3001
          command: ["node"]
          args: ["server.js"]
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 15
            periodSeconds: 10

