apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecom-backend
  template:
    metadata:
      labels:
        app: ecom-backend
    spec:
      containers:
        - name: ecom-container
          image: xhulioisufi/ecommerce:v1
          ports:
            - containerPort: 3001
          command: ["node"]
          args: ["server.js"]
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 15
            periodSeconds: 10

