apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejsapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejsapp
  template:
    metadata:
      labels:
        app: nodejsapp
    spec:
      containers:
        - name: nodejsapp-container
          image: xhulioisufi/ecommerce:v1
          ports:
            - containerPort: 3001
          command: ["node"]
          args: ["server.js"]
