apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejsapp-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejsapp-service
  template:
    metadata:
      labels:
        app: nodejsapp-service
    spec:
      containers:
        - name: nodejsapp-service
          image: xhulioisufi/ecommerce:v1
          ports:
            - containerPort: 3001
