apiVersion: v1
kind: Service
metadata:
  name: ecommerce-be-service
spec:
  selector:
    app: ecommerce-be
  ports:
    - protocol: TCP
      port: 80  
      targetPort: 3001 
  type: LoadBalancer 
